allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  sharp: true
  workerd: true
packages:
  - "examples/*"
  - "website"
  - "packages/*"
linkWorkspacePackages: true
